MUX_2_1:
	iverilog -o MUX2_1 MUXes.v MUX21_tb.v
	./MUX2_1
	gtkwave MUX_2_1.vcd
MUX_4_1:
	iverilog -o MUX4_1 MUXes.v MUX41_tb.v
	./MUX4_1
	gtkwave MUX_4_1.vcd
MUX_8_1:
	iverilog -o MUX8_1 MUXes.v MUX81_tb.v
	./MUX8_1
	gtkwave MUX_8_1.vcd
MUX_16_1:
	iverilog -o MUX16_1 MUXes.v MUX161_tb.v
	./MUX16_1
	gtkwave MUX_16_1.vcd
