DEMUX_1_2:
	iverilog -o DEMUX1_2 DEMUXes.v DEMUX_1_2_tb.v
	./DEMUX1_2
	gtkwave DEMUX_1_2.vcd
	rm DEMUX1_2
	rm DEMUX_1_2.vcd
DEMUX_1_4:
	iverilog -o DEMUX1_4 DEMUXes.v DEMUX_1_4_tb.v
	./DEMUX1_4
	gtkwave DEMUX_1_4.vcd
	rm DEMUX1_4
	rm DEMUX_1_4.vcd
DEMUX_1_16:
	iverilog -o DEMUX1_16 DEMUXes.v DEMUX_1_16_tb.v
	./DEMUX1_16
	gtkwave DEMUX_1_16.vcd
	rm DEMUX1_16
	rm DEMUX_1_16.vcd
